language: node_js
node_js:
  - 10

services:
  - postgresql
  
env:
  - DATABASE_URL=postgresql://postgres@localhost:5432/my_greetings_tests

before_script:
  - psql -c 'create database  my_greetings_tests;' -U postgres
  - psql -U postgres -d my_greetings_tests -a -f users.sql
